flowchart TD
    A[Kaggle] --> B[Python]
    B --> C[Excel]
    C --> D[Pentaho + Python]
    D --> E[Star Schema]
    E --> F[Research Database]
    F --> G[Linux]
    G --> H[Docker DBA]
    E <--> I[Developed ERD]
    H --> J[DBeaver]
    J --> K[Actual Working]
    K --> L[Future: Docker for manage]
